#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetAsyncLocalFinalizedHandleCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, :DISPATCH_FLAGS => "SA_DISPATCH_ONE")
        d.finalize(:SESSION => session)
        d.clusterNodeGetAsync(:SESSION => session, 
                              :NODE_ID => "SA_CLM_LOCAL_NODE_ID",
                              :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = NodeGetAsyncLocalFinalizedHandleCase.new()
test.run()

end # module
