#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetAsyncLocalNoCallbackCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :NO_CLUSTER_NODE_GET_CB => true, 
               :NO_CLUSTER_TRACK_CB => true, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ONE", 
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_OK)
        d.clusterNodeGetAsync(:SESSION => session, 
                              :NODE_ID => "SA_CLM_LOCAL_NODE_ID",
                              :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INIT)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = NodeGetAsyncLocalNoCallbackCase.new()
test.run()

end # module
