#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetAsyncLocalFinalizedHandleCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.init(resource, true, false, "SA_DISPATCH_ONE", 
               SAFTestUtils.SA_AIS_OK)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.clusterNodeGetAsync(resource, "SA_CLM_LOCAL_NODE_ID", nil,
                              SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteTestResource(resource)
        passed()
    end
end

test = NodeGetAsyncLocalFinalizedHandleCase.new()
test.run()

end # module
