#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class DispatchOneCase < SAFTestCase
    @@TIMES_TO_RUN = 3

    def initialize()
        super()
    end
     
    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession(:DISPATCH_FLAGS =>
                                              "SAFTEST_DISPATCH_NONE")
        invocation = d.generateInvocation()
        d.clusterNodeGetResetCBCount(:SESSION => session)
        d.clusterNodeGetCBCount(:SESSION => session, :EXPECTED_COUNT => 0)
        @@TIMES_TO_RUN.times do
            d.clusterNodeGetAsyncWithInvocation(:SESSION => session,
                                                :INVOCATION => invocation,
                                                :NODE_ID => "SA_CLM_LOCAL_NODE_ID")
        end

        for i in 1..@@TIMES_TO_RUN
            d.dispatch(:SESSION => session,
                       :DISPATCH_FLAGS => "SA_DISPATCH_ONE")
            d.clusterNodeGetCBCount(:SESSION => session,
                                    :EXPECTED_COUNT => i)
        end
        passed()
    end
end

test = DispatchOneCase.new()
test.run()

end # module
