#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class DispatchAllInvalidFlagsCase < SAFTestCase
    def initialize()
        super()
    end
     
    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession(:DISPATCH_FLAGS =>
                                              "SAFTEST_DISPATCH_NONE")
        d.dispatch(:SESSION => session, 
                   :DISPATCH_FLAGS => "SA_DISPATCH_INVALID",
                   :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        passed()
    end
end

test = DispatchAllInvalidFlagsCase.new()
test.run()

end # module
