#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class DispatchAllInvalidHandleCase < SAFTestCase
    def initialize()
        super()
    end
     
    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.dispatch(:SESSION => session, 
                   :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
                   :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = DispatchAllInvalidHandleCase.new()
test.run()

end # module
