#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class AsyncLockEXCase < SAFTestCase
    @@INVOCATION = $$

    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d.selectObjectGet(:SESSION => session)
        d.resourceOpen(:SESSION => session, 
                       :LOCK_NAME => "AsyncLockExclusive")
        d.lockAsync(:SESSION => session, :LOCK_MODE => 'EX', 
                    :INVOCATION => @@INVOCATION)
        d.waitForLockAsyncLockStatus(:SESSION => session,
                                     :EXPECTED_INVOCATION => @@INVOCATION,
                                     :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_GRANTED')
        d.resourceClose(:SESSION => session)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = AsyncLockEXCase.new()
test.run()

end # module
