#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class AsyncLockEXCase < SAFTestCase
    @@INVOCATION = $$

    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.startNewShortLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d.selectObjectGet(:SESSION => session)
        d.resourceOpen(:SESSION => session, 
                       :LOCK_NAME => "AsyncLockExclusive")
        d.lockAsync(:SESSION => session, :LOCK_MODE => 'EX', 
                    :INVOCATION => @@INVOCATION)
        d.waitForLockAsyncLockStatus(:SESSION => session, 
                                     :EXPECTED_INVOCATION => @@INVOCATION,
                                     :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_GRANTED')
        d1 = LCKTestDriver.startNewShortLivedDriver()
        session1 = d1.createShortLivedSession()
        d1.init(:SESSION => session1, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d1.selectObjectGet(:SESSION => session1)
        d1.resourceOpen(:SESSION => session1, 
                        :LOCK_NAME => "AsyncLockExclusive")
        d1.lockAsync(:SESSION => session1, :LOCK_MODE => 'PR', 
                     :INVOCATION => @@INVOCATION, 
                     :LOCK_FLAG_NO_QUEUE => true)

        d1.waitForLockAsyncLockStatus(:SESSION => session1, 
                                      :EXPECTED_INVOCATION => @@INVOCATION,
                                      :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_NOT_QUEUED')
        d.resourceClose(:SESSION => session)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        d.stop()

        d1.resourceClose(:SESSION => session1)
        d1.finalize(:SESSION => session1)
        d1.deleteSession(:SESSION => session1)
        d1.stop()
        passed()
    end
end

test = AsyncLockEXCase.new()
test.run()

end # module
