#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class DispatchAllFinalizedHandleCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.init(resource, true, true, true, true,
               "SA_DISPATCH_ALL", SAFTestUtils.SA_AIS_OK)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.dispatch(resource, "SA_DISPATCH_ALL",
                   SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteTestResource(resource)
        passed()
    end
end

test = DispatchAllFinalizedHandleCase.new()
test.run()

end # module
