#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class DispatchBlockingLckCase < SAFTestCase
    @@INVOCATION = $$
    @@WAITER_SIGNAL = $$
    def initialize()
        super()
    end

    def run()
        d1 = LCKTestDriver.getRandomLongLivedDriver(:THREADED => true)
        session1 = d1.getRandomLongLivedSession(:GLOBAL => true,
                                     :DISPATCH_FLAGS => "SA_DISPATCH_BLOCKING")
        
        d1.resourceOpen(:SESSION => session1, :LOCK_NAME => "dpBlkg")
        d1.lockSync(:SESSION => session1, :LOCK_MODE => 'EX',
                    :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_GRANTED')

        d2 = LCKTestDriver.getRandomLongLivedDriver()
        session2 = d2.createShortLivedSession()
        d2.init(:SESSION => session2, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d2.resourceOpen(:SESSION => session2, :LOCK_NAME => "dpBlkg")
        d2.lockAsync(:SESSION => session2, :LOCK_MODE => 'EX', 
                     :INVOCATION => @@INVOCATION + 1, 
                     :WAITER_SIGNAL => @@WAITER_SIGNAL)

        session3 = d2.createShortLivedSession()
        d2.init(:SESSION => session3, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d2.resourceOpen(:SESSION => session3, :LOCK_NAME => "dpBlkg")
        d2.lockAsync(:SESSION => session3, :LOCK_MODE => 'EX', 
                     :INVOCATION => @@INVOCATION + 2, 
                     :WAITER_SIGNAL => @@WAITER_SIGNAL)

        # thread is already sitting in saLckDispatch(DISPATCH_BLOCKING), 
        # so the notifications should have gotten there already.
        d1.lockGetWaitCount(:SESSION => session1,
                            :EXPECTED_LAST_WAITER_SIGNAL => @@WAITER_SIGNAL, 
                            :EXPECTED_NOTIFICATION_COUNT => 2) 

        d2.resourceClose(:SESSION => session2)
        d2.finalize(:SESSION => session2)
        d2.deleteSession(:SESSION => session2)

        d2.resourceClose(:SESSION => session3)
        d2.finalize(:SESSION => session3)
        d2.deleteSession(:SESSION => session3)

        passed()
    end
end


test = DispatchBlockingLckCase.new()
test.run()

end #module
