#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackStopWithTrackCurrentCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        xmlFile = tmpFile("cluster_track")
        numberOfItems = d.getImplementation().getCluster().getNodes().length

        d.init(resource, true, true, "SA_DISPATCH_ONE",
               SAFTestUtils.SA_AIS_OK)
        d.selectObjectGet(resource, false, SAFTestUtils.SA_AIS_OK)
        d.clusterTrack(resource, true, false, false,
                             false, false,
                             false, numberOfItems,
                             xmlFile, SAFTestUtils.SA_AIS_OK)
        d.clusterTrackStop(resource, SAFTestUtils.SA_AIS_ERR_NOT_EXIST)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.deleteTestResource(resource)
        passed()
    end
end


test = ClusterTrackStopWithTrackCurrentCase.new()
test.run()

end # module
