#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackStopWithTrackCurrentCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        validateCluster = d.getImplementation().getCluster()
        numberOfItems = validateCluster.getNodes().length
        d.clusterTrackWithNoReformation(:SESSION => session, 
                                        :TRACK_CURRENT => true,
                                        :NUMBER_OF_ITEMS => numberOfItems,
                                        :VALIDATE_CLUSTER => validateCluster)
        d.clusterTrackStop(:SESSION => session, 
                           :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_NOT_EXIST)
        passed()
    end
end


test = ClusterTrackStopWithTrackCurrentCase.new()
test.run()

end # module
