#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackChangesStopTwiceCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        d.clusterTrackWithNoReformation(:SESSION => session, 
                                        :TRACK_CHANGES => true, 
                                        :NULL_NOTIFICATION_BUFFER => true, 
                                        :NULL_CLUSTER_NOTIFICATION => true)
        d.clusterTrackStop(:SESSION => session)
        d.clusterTrackStop(:SESSION => session, 
                           :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_NOT_EXIST)
        passed()
    end
end


test = ClusterTrackChangesStopTwiceCase.new()
test.run()

end # module
