#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetLocalZeroTimeoutCase < SAFTestCase 

    def initialize()
      super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        validateNode = d.getImplementation().getCluster().getLocalNode()
        d.clusterNodeGet(:SESSION => session, 
                         :NODE_ID => "SA_CLM_LOCAL_NODE_ID", 
                         :TIMEOUT => 0, 
                         :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_TIMEOUT)
        passed()
    end
end


test = NodeGetLocalZeroTimeoutCase.new()
test.run()

end # module

