#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']] 
$: << clmDir
require 'CLMTestDriver'

class NodeGetLocalNullClusterNodeCase < SAFTestCase 

    def initialize()
      super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        nodeID = "SA_CLM_LOCAL_NODE_ID"
        d.clusterNodeGet(:SESSION => session,
                         :NODE_ID => "SA_CLM_LOCAL_NODE_ID", 
                         :NULL_CLUSTER_NODE => true,
                         :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        passed()
    end
end

test = NodeGetLocalNullClusterNodeCase.new()
test.run()

end # module
