#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        validateNode = nil

        nodeIDParam = getParam('node-id')
        if nodeIDParam == 'local'
            validateNode = d.getImplementation().getCluster().getLocalNode()
            nodeID = "SA_CLM_LOCAL_NODE_ID"
        elsif nodeIDParam == 'random'
            validateNode = d.getImplementation().getCluster().getRandomNode()
            nodeID = validateNode.getID()
        else
            raise "Invalid nodeIDParam #{nodeIDParam}"
        end
            
        d.clusterNodeGet(:SESSION => session, :NODE_ID => nodeID, 
                         :TIMEOUT => "SA_TIME_MAX", 
                         :VALIDATE_NODE => validateNode)
        passed()
    end
end

test = NodeGetCase.new()
test.run()

end # module
