#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']] 
$: << clmDir
require 'CLMTestDriver'

class NodeGetLocalNullClusterNodeCase < SAFTestCase 

    def initialize()
      super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        nodeID = "SA_CLM_LOCAL_NODE_ID"
        d.clusterNodeGet(resource, nodeID, "SA_TIME_MAX", true,
                         nil, SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.deleteTestResource(resource)
        passed()
    end
end

test = NodeGetLocalNullClusterNodeCase.new()
test.run()

end # module
