#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class NodeGetLocalZeroTimeoutCase < SAFTestCase 

    def initialize()
      super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.getRandomLongLivedTestResource()
       
        validateNode = d.getImplementation().getCluster().getLocalNode()
        nodeID = "SA_CLM_LOCAL_NODE_ID"
 
        d.clusterNodeGet(resource, "SA_CLM_LOCAL_NODE_ID", 0, false,
                         nil, SAFTestUtils.SA_AIS_ERR_TIMEOUT)
        passed()
    end
end


test = NodeGetLocalZeroTimeoutCase.new()
test.run()

end # module

