#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackCurrentWithoutInitCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.clusterTrack(:SESSION => session, 
                       :TRACK_CURRENT => true,
                       :NULL_NOTIFICATION_BUFFER => true,
                       :NULL_CLUSTER_NOTIFICATION => true,
                       :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = ClusterTrackCurrentWithoutInitCase.new()
test.run()

end # module
