#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackChangesAndChangesOnlyCase < SAFTestCase
    def initialize()
        super()
    end 
    
    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        d.clusterTrack(:SESSION => session, 
                       :TRACK_CHANGES => true, 
                       :TRACK_CHANGES_ONLY => true, 
                       :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_BAD_FLAGS)
        passed()
    end
end

test = ClusterTrackChangesAndChangesOnlyCase.new()
test.run()

end # module
