#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackInvalidNumberOfItemsCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession()
        d.clusterTrack(:SESSION => session, 
                       :TRACK_CURRENT => true, 
                       :NUMBER_OF_ITEMS => 0,
                       :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        passed()
    end
end

test = ClusterTrackInvalidNumberOfItemsCase.new()
test.run()

end # module
