#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class ClusterTrackCurrentNoCallbackCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :NO_CLUSTER_NODE_GET_CB => TRUE,
               :NO_CLUSTER_TRACK_CB => TRUE,
               :DISPATCH_FLAGS => "SA_DISPATCH_ONE")
        d.selectObjectGet(:SESSION => session)
        d.clusterTrack(:SESSION => session, 
                       :TRACK_CURRENT => true, 
                       :NULL_NOTIFICATION_BUFFER => true, 
                       :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INIT)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = ClusterTrackCurrentNoCallbackCase.new()
test.run()

end # module
