#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class SelectionObjectGetNullSelectionObjectCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.getRandomLongLivedSession(:DISPATCH_FLAGS =>
                                              "SAFTEST_DISPATCH_NONE")
        d.selectObjectGet(:SESSION => session, 
                          :NULL_SELECTION_OBJECT => true, 
                          :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        passed()
    end
end

test = SelectionObjectGetNullSelectionObjectCase.new()
test.run()

end # module
