#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class SelectionObjectGetFinalizedHandleCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.init(resource, true, false, "SA_DISPATCH_ALL",
               SAFTestUtils.SA_AIS_OK)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.selectObjectGet(resource, true, 
                          SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.deleteTestResource(resource)
        passed()
    end
end

test = SelectionObjectGetFinalizedHandleCase.new()
test.run()

end # module
