#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class SelectionObjectGetFinalizedHandleCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d.finalize(:SESSION => session)
        d.selectObjectGet(:SESSION => session,
                          :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_BAD_HANDLE)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = SelectionObjectGetFinalizedHandleCase.new()
test.run()

end # module
