#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeTwiceCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_OK)
        d.init(:SESSION => session, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_OK)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = InitializeTwiceCase.new()
test.run()

end # module

