#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeNullCallbacksCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.initWithOptions(resource, "SA_DISPATCH_ALL",
                          SAFTestUtils.SA_AIS_RELEASE_CODE,
                          SAFTestUtils.SA_AIS_MAJOR_VERSION,
                          SAFTestUtils.SA_AIS_MINOR_VERSION,
                          false, true, false,
                          SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.deleteTestResource(resource)
        passed()
    end
end

test = InitializeNullCallbacksCase.new()
test.run()

end # module
