#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeNullCallbacksCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
               :NULL_CALLBACKS => true,
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = InitializeNullCallbacksCase.new()
test.run()

end # module
