#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeInvalidVersionCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.initWithOptions(resource, "SA_DISPATCH_ALL", 
                          0, 0, 0, 
                          false, false, false,
                          SAFTestUtils.SA_AIS_ERR_VERSION)
        d.deleteTestResource(resource)
        passed()
    end
end

test = InitializeInvalidVersionCase.new()
test.run()

end # module

