#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeTwiceCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.init(resource, true, true, "SA_DISPATCH_ALL",
                       SAFTestUtils.SA_AIS_OK)
        d.initWithOptions(resource, "SA_DISPATCH_ALL", 
                          0, 0, 0, 
                          false, false, false,
                          SAFTestUtils.SA_AIS_ERR_VERSION)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.deleteTestResource(resource)
        passed()
    end
end

test = InitializeTwiceCase.new()
test.run()

end # module

