#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class InitializeInvalidVersionCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = CLMTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session,
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
               :VERSION_RELEASE_CODE => 0,
               :VERSION_MAJOR => 0,
               :VERSION_MINOR => 0,
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_VERSION)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = InitializeInvalidVersionCase.new()
test.run()

end # module

