#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class FinalizeCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        @implementation.getCluster().getNodes().each do |node|
            CLMTestDriver.getLongLivedDrivers(node).each do |d|
                d.getAllLongLivedTestResources().each do |r|
                    d.finalize(r, SAFTestUtils.SA_AIS_OK)
                    d.deleteTestResource(r)
                end
            end
        end
        passed()
    end
end

test = FinalizeCase.new()
test.run()

end # module
