#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

clmDir = "%s/cases/clm" % [ENV['SAFTEST_ROOT']]
$: << clmDir
require 'CLMTestDriver'

class FinalizeCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        @implementation.getCluster().getLongLivedNodes().each do |node|
            CLMTestDriver.getLongLivedDrivers(:NODE => node).each do |d|
                d.getAllLongLivedSessions().each do |r|
                    d.finalize(:SESSION => r)
                    d.deleteSession(:SESSION => r)
                end
            end
        end
        passed()
    end
end

test = FinalizeCase.new()
test.run()

end # module
