#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class UnlockPRSyncLockCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d.resourceOpen(:SESSION => session, :LOCK_NAME => "lock1")
        d.lockSync(:SESSION => session, :LOCK_MODE => 'PR', 
                   :LOCK_FLAG_NO_QUEUE => true,
                   :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_GRANTED')
        d.unlockSync(:SESSION => session)
        d.resourceClose(:SESSION => session)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = UnlockPRSyncLockCase.new()
test.run()

end # module
