#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class LockEXCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d1 = LCKTestDriver.startNewShortLivedDriver(nil)
        resource1 = d1.createShortLivedTestResource()
        d1.init(resource1, true, true, true, true,
                "SA_DISPATCH_ALL", SAFTestUtils.SA_AIS_OK)
        d1.resourceOpen(resource1, "lock1", SAFTestUtils.SA_AIS_OK)
        d1.lockSync(resource1, 'EX', 0, false, false, true, false, false,
                   'SA_LCK_LOCK_GRANTED', SAFTestUtils.SA_AIS_OK)

        d2 = LCKTestDriver.getRandomLongLivedDriver(nil)
        resource2 = d2.createShortLivedTestResource()
        d2.init(resource2, true, true, true, true,
                "SA_DISPATCH_ALL", SAFTestUtils.SA_AIS_OK)
        d2.resourceOpen(resource2, "lock1", SAFTestUtils.SA_AIS_OK)
        action = d2.lockSyncBG(resource2, 'EX', 0, false, false, 
                               false, false, false, 'SA_LCK_LOCK_GRANTED')
        sleep(5)
        d1.stop()
        d2.waitForLockSyncBG(action, SAFTestUtils.SA_AIS_OK)

        d2.resourceClose(resource2, SAFTestUtils.SA_AIS_OK)
        d2.finalize(resource2, SAFTestUtils.SA_AIS_OK)
        d2.deleteTestResource(resource2)
        passed()
    end
end

test = LockEXCase.new()
test.run()

end # module
