#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class LockEXNullLockIDCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, :DISPATCH_FLAGS => "SA_DISPATCH_ALL")
        d.resourceOpen(:SESSION => session, 
                       :LOCK_NAME => "LockExclusiveNullID")
        d.lockSync(:SESSION => session, :LOCK_MODE => 'EX', 
                   :NULL_LOCK_ID => true, :LOCK_FLAG_NO_QUEUE => true, 
                   :EXPECTED_LOCK_STATUS => 'SA_LCK_LOCK_GRANTED', 
                   :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.resourceClose(:SESSION => session)
        d.finalize(:SESSION => session)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = LockEXNullLockIDCase.new()
test.run()

end # module
