#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestUtils'
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']] 
$: << lckDir
require 'LCKTestDriver'

class InitializeNullHandleCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.initWithOptions(resource, "SA_DISPATCH_ALL",
                          SAFTestUtils.SA_AIS_RELEASE_CODE,
                          SAFTestUtils.SA_AIS_MAJOR_VERSION,
                          SAFTestUtils.SA_AIS_MINOR_VERSION,
                          true, false, false,
                          SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.deleteTestResource(resource)
        passed()
    end
end

test = InitializeNullHandleCase.new()
test.run()

end # module

