#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'
require 'SAFTestUtils'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class InitializeNullHandleCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver()
        session = d.createShortLivedSession()
        d.init(:SESSION => session, 
               :DISPATCH_FLAGS => "SA_DISPATCH_ALL",
               :NULL_VERSION => true,
               :EXPECTED_RETURN => SAFTestUtils.SA_AIS_ERR_VERSION)
        d.deleteSession(:SESSION => session)
        passed()
    end
end

test = InitializeNullHandleCase.new()
test.run()

end # module
