#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class InitializeInvalidVersionCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.initWithOptions(resource, "SA_DISPATCH_ALL",
                          0, 0, 0,
                          false, false, false,
                          SAFTestUtils.SA_AIS_ERR_VERSION)
        d.deleteTestResource(resource)
        passed()
    end
end

test = InitializeInvalidVersionCase.new()
test.run()

end # module
