#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class InitializeCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        @implementation.getCluster().getLongLivedNodes().each do |node|
        LCKTestDriver.getLongLivedDrivers(node).each do |d|
            resource = d.createLongLivedTestResource()
            d.init(resource, true, true, true, true, "SA_DISPATCH_ALL",
                   SAFTestUtils.SA_AIS_OK)
            end
        end
        passed()
    end
end

test = InitializeCase.new()
test.run()

end # module
