#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" % [ENV['SAFTEST_ROOT']]
$: << lckDir
require 'LCKTestDriver'

class SelectionObjectGetNullSelectionObjectCase  < SAFTestCase
    def initialize()
        super()
    end

    def run()
        d = LCKTestDriver.getRandomLongLivedDriver(nil)
        resource = d.createShortLivedTestResource()
        d.init(resource, true, true, true, true, "SA_DISPATCH_ALL",
               SAFTestUtils.SA_AIS_OK)
        d.selectObjectGet(resource, true, 
                          SAFTestUtils.SA_AIS_ERR_INVALID_PARAM)
        d.finalize(resource, SAFTestUtils.SA_AIS_OK)
        d.deleteTestResource(resource)
        passed()
    end
end

test = SelectionObjectGetNullSelectionObjectCase.new()
test.run()

end # module
