#!/usr/bin/ruby

module SAFTest

$: << "%s/lib" % [ENV['SAFTEST_ROOT']]
require 'SAFTestCase'

lckDir = "%s/cases/lck" %  [ENV['SAFTEST_ROOT']] 
$: << lckDir
require 'LCKTestDriver'

class FinalizeCase < SAFTestCase
    def initialize()
        super()
    end

    def run()
        @implementation.getCluster().getNodes().each do |node|
            LCKTestDriver.getLongLivedDrivers(node).each do |d|
                d.getAllTestResources().each do |r|
                    d.finalize(r, SAFTestUtils.SA_AIS_OK)
                    d.deleteTestResource(r)
                end
            end
        end
        passed()
    end
end

test = FinalizeCase.new()
test.run()

end # module
